### ISSUE TITLE
Update docs for Python 3.7

### ISSUE THREAD

**Issue by and-semakin** [alex-sherman/unsync#10]
Examples in README should be updated for Python 3.7.

```python
async def sync_async():
    await asyncio.sleep(0.1)
    return 'I hate event loops'

result = asyncio.run(sync_async())
print(result)
```

Now it gets simpler with regular `asyncio` functions but `unsync` still do its good magic :)

**Comment by Luttik** [comment]
Since 3.8 `asyncio.run` is [the official preferred method for running asyncio programs](**https://docs.python.org/3/whatsnew/3.8.html**). I will include this in my next pull request.
