### ISSUE TITLE
Unclear how async methods should make use of unsync methods

### ISSUE THREAD

**Issue by narfanar** [alex-sherman/unsync#12]
You can't (from what I tried) `await some_unsync()`.

Looked into it a bit and it seems to be a misunderstanding on my part. This library isn't actually meant to help with this. There was a comment on a reddit thread by the author that gave an example of 'async'ifying a `requests.get` call, but, being not natively async, it's near useless for use alongside normal async functions.

(I'm beginning to think async in Python is just hopeless.)

**Comment by alex-sherman** [comment]
Could you provide a more full example of what you're trying to do and what error you're getting? Unsync functions should be awaitable.

**Comment by alex-sherman** [comment]
Without more context I can't provide any assistance on this issue. Please feel free to follow up and I'll reopen this issue.
