### ISSUE TITLE
Defining the amount of threads in use for sync functions

### ISSUE THREAD

**Issue by ivergara** [alex-sherman/unsync#19]
How is the number of threads launched for an asynchronous function being decorated with `unsync`? Is there a possibility to define that number? If it's not possible out of the box, how could I start approaching that?

**Comment by alex-sherman** [comment]
The async loop runs in a [single thread](https://github.com/alex-sherman/unsync/blob/ec2d07efd3293545729563082da7ec3efc7094b6/unsync/unsync.py#L134) and "regular" functions decorated with `@unsync` without setting `cpu_bound = True` will run in a [ThreadPoolExecutor](https://github.com/alex-sherman/unsync/blob/ec2d07efd3293545729563082da7ec3efc7094b6/unsync/unsync.py#L12).

Assuming your referring to the later, without any arguments ThreadPoolExecutor will [overprovision (see `max_workers`)](https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.ThreadPoolExecutor) in Python 3.5 and later. It creates 5 threads per core. If that's insufficient I think you can just overwrite `unsync.thread_executor = concurrent.futures.ThreadPoolExecutor(max_workers = 9000)`.

I'm curious what your workload is that would you would notice this, is it really doing hundreds of IO bound operations?

**Comment by ivergara** [comment]
Thanks for the answer. Indeed it was the later.

I'm not noticing it at the moment, but I was preemptively wondering how to control the number of threads, particularly at different steps. For example, due to a limitation on external resources, I could be limited by the number of threads accessing that resource but then local downstream processing could benefit from more threads.

**Comment by alex-sherman** [comment]
Makes sense. I'll close this for now since I think just assigning over `unsync.thread_executor` will cover your scenario.

Feel free to reopen, or open a PR if you'd like to add a cleaner API or something for setting the number of threads. My own opinion is that a function like `unsync.set_max_thread_workers(n)` is less clean than just assigning to `thread_executor`.
