### ISSUE TITLE
asherman.io unsync page typo, or not

### ISSUE THREAD

**Issue by bkcsfi** [alex-sherman/unsync#2]
Howdy,

This page has some amusing bits http://asherman.io/projects/unsync.html

but possibly this wasn't an intended joke

```makes its own in a new thread whose soul purpose```

Did you mean

```makes its own in a new thread whose sole purpose```

it kind of reads ok with 'soul', but I think Unfuture is more likely to have a soul, since it embodies the spirit of two Futures

**Comment by alex-sherman** [comment]
Definitely unintended, but glad it got a laugh.

Thanks for pointing it out!
