### ISSUE TITLE
Can't Import unsync on AWS Lambda

### ISSUE THREAD

**Issue by simplynd** [alex-sherman/unsync#21]
I am trying to use the unsync module with AWS Lambda but everytime I try to import unsync my lambda execution fails with following error.

"module initialization error: [Errno 38] Function not implemented"

**Comment by alex-sherman** [comment]
Can you include the full stack trace? Based on issues like https://github.com/numba/numba/issues/3344 I'm assuming this is due to AWS lambda not supporting the multiprocessing library.

**Comment by simplynd** [comment]
Unfortunately, it's not printing any Trace or details on Error.  

I suspect the same as many of my search indicated that AWS doesn't support multiprocessing or to you have to use some workaround to do multi threading

**Comment by simplynd** [comment]
@alex-sherman 

I was able to get Stack trace. Please see below.  I read it on a seperate thread that AWS Lambda gives error when trying to use multiprocessing.queues instead suggestion was to use multiprocessing.pipes.  

Not sure if that is something you would be interested in exploring with unsync.

{
  "errorMessage": "[Errno 38] Function not implemented",
  "errorType": "OSError",
  "stackTrace": [
    "  File \"/var/task/lambda_function.py\", line 7, in lambda_handler\n    thesync.main()\n",
    "  File \"/var/task/thesync.py\", line 13, in main\n    compute_some(),\n",
    "  File \"/var/task/unsync.py\", line 55, in __call__\n    unsync.process_executor = concurrent.futures.ProcessPoolExecutor()\n",
    "  File \"/var/lang/lib/python3.7/concurrent/futures/process.py\", line 556, in __init__\n    pending_work_items=self._pending_work_items)\n",
    "  File \"/var/lang/lib/python3.7/concurrent/futures/process.py\", line 165, in __init__\n    super().__init__(max_size, ctx=ctx)\n",
    "  File \"/var/lang/lib/python3.7/multiprocessing/queues.py\", line 42, in __init__\n    self._rlock = ctx.Lock()\n",
    "  File \"/var/lang/lib/python3.7/multiprocessing/context.py\", line 67, in Lock\n    return Lock(ctx=self.get_context())\n",
    "  File \"/var/lang/lib/python3.7/multiprocessing/synchronize.py\", line 162, in __init__\n    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)\n",
    "  File \"/var/lang/lib/python3.7/multiprocessing/synchronize.py\", line 59, in __init__\n    unlink_now)\n"
  ]
}

**Comment by alex-sherman** [comment]
I believe each lambda instance gets only one core, so it makes sense that they would not support multiprocessing. Luckily with #18 merged in, you should be able to avoid instantiating a `multiprocessing.Pool` by setting `cpu_bound=False` or just omitting it (False is the default).

**Comment by simplynd** [comment]
Thank you so much. It works with your suggestion, and unsync makes life so much easier.
