### ISSUE TITLE
CPU bound coroutines

### ISSUE THREAD

**Issue by mikeckennedy** [alex-sherman/unsync#3]
Hi. Love unsync. I've always felt C#'s async / await implementation was much slicker than Python's and you bring much of that to Python with barely over 100 lines of code. Well done.

I do have one issue to report. If I have the following:

```python
@unsync(cpu_bound=True)
async def compute_some():
    print("Computing {}...".format(process_info()))
    for _ in range(1, 10_000_000):
        math.sqrt(25 ** 25 + .01)
```

This runs on the asyncio loop even though `cpu_bound=True`. The reason is `async def`  has higher priority. 

I'd suggest one of two changes.

1. Go ahead and run this in a separate multiprocess execution and just create an asyncio loop to run it.
2. Raise an error saying `cpu_bound` cannot be paired with an async coroutine and instruct them to remove `cpu_bound=True` or change ` async def` to `def`.

I'm partial to 1, but either would be better than ignoring the `cpu_bound` setting.

Thanks!

**Comment by alex-sherman** [comment]
Thanks for finding this! I'm opting to raise an error (at least for now) to keep complexity down. I think it's still possible to achieve functions that are both async and use cpu_bound=True, but they need to be split up into parts that require only one or the other. Maybe that is too cumbersome, and maybe that will change in the future.

I pushed a new version to pip and have the commit for you to look at if you're curious.

**Comment by mikeckennedy** [comment]
Perfect, thank you Alex! Also, I'm featuring unsync in a new course I'm writing on async programming Python over at https://training.talkpython.fm/
