### ISSUE TITLE
Support naive introspection for wrapped functions

### ISSUE THREAD

**Issue by jcass77** [alex-sherman/unsync#4]
It does not seem like the ``@unsync`` decorator can currently be used as part of a nested decorator chain.

For example, trying to use ``unsync`` in a pytest fixture: 
```
@pytest.fixture
@unsync
async def my_test_fixture():
    pass
```

...fails with ``@unsync E   AttributeError: 'unsync' object has no attribute '__name__'``

This limits the range of scenarios that ``unsync`` can be used in.

**Comment by alex-sherman** [comment]
Thanks for adding support for this, and for including unit tests! Very much appreciate that!
