### ISSUE TITLE
Continuation with cpu_bound functions

### ISSUE THREAD

**Issue by danhje** [alex-sherman/unsync#40]
Using a cpu_bound function in a continuation chain currently fails. Example: 
```python
from unsync import unsync
import asyncio
import time

@unsync()
async def download_data(url):
    await asyncio.sleep(1)
    return 'data'

@unsync(cpu_bound=True)
def process_data(task):
    data = task.result()
    time.sleep(1)
    return 'processed data'

@unsync()
def store_processed_data(task):
    data = task.result()
    time.sleep(1)
    print('Stored')

tasks = [
    download_data(url).then(process_data).then(store_processed_data)
    for url in ['url1', 'url2', 'url3']
]

[task.result() for task in tasks]

# TypeError: cannot pickle '_asyncio.Task' object
```

I think this is a fairly large drawback. It could easily be solved by passing the `result()` to the continuation rather than the Unfuture. If there are good reasons for passing the Unfuture, perhaps it could somehow be made picklable, or the unpicklable parts could be stripped / swapped out before passing it on.

**Comment by alex-sherman** [comment]
I started #41, not sure exactly why I chose this API in the first place. It doesn't really seem like any reason to pass the Unfuture.

Let me think about this a bit since it's a breaking change, but looks fine at first glance.

**Comment by danhje** [comment]
Great! It’s worth remembering that it will still only work with a result that can be picked.
