### ISSUE TITLE
Using @unsync decorator in Jupyter results in error

### ISSUE THREAD

**Issue by StevenBorg** [alex-sherman/unsync#43]
Running the example code, but inside a Jupiter notebook results in the following error:
TypeError: 'module' object is not callable

Here's the code in a single Jupyter cell, running Python 3.7.7

import unsync

@unsync
async def unsync_async():
    await asyncio.sleep(1)
    return 'I like decorators'

unfuture1 = unsync_async()
unfuture2 = unsync_async()
print(unfuture1.result() + unfuture2.result())

**Comment by alex-sherman** [comment]
Replace the first line with `from unsync import unsync`
