### ISSUE TITLE
closing old processes

### ISSUE THREAD

**Issue by 0xstochastic** [alex-sherman/unsync#49]
Hi,
After running my script that uses unsync (thank you so much for this great tool!!) for a couple of hours my os starts complaining about all the open processes. I read that setting `unsync.process_executor = None` would clean out old processes, but I'm getting `AttributeError: can't set attribute` when executing that line in my code.

**Comment by alex-sherman** [comment]
Can you provide some code that reproduces the error?

**Comment by 0xstochastic** [comment]
I have found that the bug in my code was not caused by unsync but by the multiprocessing library. After switching 100% to unsync the problem disappeared. 
Sorry for taking up your time and thanks again for your great library!

**Comment by alex-sherman** [comment]
👍
