### ISSUE TITLE
Incorrect import in README

### ISSUE THREAD

**Issue by markjr-cisco** [alex-sherman/unsync#51]
The import should read
```python
from unsync import unsync
```
not
```python
import unsync
```
When I try running the sample code, I get an error
```
TypeError: 'module' object is not callable
```

**Comment by alex-sherman** [comment]
Thanks for pointing that out! Fixed in [fe42909](https://github.com/alex-sherman/unsync/commit/fe42909ee77706be995914b91e6d5780fdeacc53).
