### ISSUE TITLE
Why not use unittest's assertRaises instead of pytest.raises?

### ISSUE THREAD

**Issue by and-semakin** [alex-sherman/unsync#7]
In tests:

```python
    def test_exception(self):
        class TestException(Exception):
            pass

        @unsync
        async def error():
            await asyncio.sleep(0.1)
            raise TestException

        with raises(TestException):  # pytest.raises
            error().result()
```
but [self.assertRaises](https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertRaises) would do the same:

```python
        with self.assertRaises(TestException):
            error().result()
```

I think it would be nice to not have any 3rd-party dependencies at all, even in tests. Or maybe there is some tricky difference?

**Comment by alex-sherman** [comment]
Good eye! I did not know about self.assertRaises in unittest. If you'd like attribution, feel free to submit a pull request otherwise I'll check something in.

**Comment by and-semakin** [comment]
Happy to do a PR

**Comment by and-semakin** [comment]
Done

**Comment by alex-sherman** [comment]
Thanks for putting that together!
